version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk # java 8
    steps:
      - checkout
      - run:
          name: Run tests 
          command: |
            build/sbt "++ 2.12.8 coreTest/test"
            build/sbt "++ 2.12.8 hiveMR/test"
            build/sbt "++ 2.12.8 hiveTez/test"
            build/sbt "++ 2.11.12 coreTest/test"
            build/sbt "++ 2.11.12 hiveMR/test"
            build/sbt "++ 2.11.12 hiveTez/test"
